name: Android Build and Release

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build-apk.yml'
      - 'app/**'
      - 'commonlibrary/**'
      - 'zaplibrary/**'

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission to Gradle
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew app:assemble

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files:  app/build/outputs/apk/debug/app-debug.apk
